apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30036  # You can change this if needed (range: 30000–32767)
